
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-app
        ports:
            - 8000:8000
        volumes:
            - .:/var/www/html
        networks:
            - laravel-network
        depends_on:
            - db

    db:
        image: mysql:8.0
        container_name: laravel-db
        ports:
            - 3307:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel_db
            MYSQL_USER: laravel_user
            MYSQL_PASSWORD: laravel_password
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - laravel-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - 8080:80
        environment:
            PMA_HOST: db
            PMA_USER: laravel_user
            PMA_PASSWORD: laravel_password
        networks:
            - laravel-network

volumes:
    db_data:

networks:
    laravel-network:
